### ISSUE TITLE
Emoji from higher android versions

### ISSUE THREAD

**Issue by Stanwarr** [Nordskog/SwiftKeyExi#14]
So as you know emojis get regularly updated on newer phones but old phones with the old Android versions are left alone with no update yet we can manually add new emojis fonts from higher android versions yet the emoji panel of SwiftKey when we install new emojis does not add to the new ones. For example I'm currently on Android 4.4.4. SwiftKey emoji panel shows only the emojis that are available for that specific Android version. Say I updated my font to the latest one and got new (totally new I don't mean updated) emojis like 🤔 and many others, these won't show up at the emoji panel of SwiftKey. My suggestion is to allow us to customize the panel or anything else to allow us to use the newly added emojis easily.

**Comment by Nordskog** [comment]
Exi already supports customizing the emoji panels. If you have the "Use Exi emoji panel" option checked under settings, it will use the emoji panels configured in Exi instead of the stock Swiftkey ones.

Up until Marshmallow Swiftkey used the same set of emoji panels, only replacing them with a new set for Nougat. Exi for Swiftkey starts you off with the the same of panels, replacing them if you update to Nougat.

Currently you could just make a few text files containing all the emoji you want (one emoji per line), and importing them.

That would of course be a bit of a drag, so with commit https://github.com/Nordskog/SwiftKeyExi/commit/e6ec3ea922d6c10453728aa624c3fbc8ffaaaa24 I've added the option to manually set whether you want the pre- or post nougat stock emoji panels: https://i.imgur.com/StuHlo4.png

I'm waiting a bit hoping that the translators find the time to translate the new strings before I release, but it should be available in Exi for Swiftkey 1.2.1 in a day or two.

**Comment by Nordskog** [comment]
Implemented in Exi for Swiftkey 1.2.1, which is now released.
