### ISSUE TITLE
[feature request] Remove whitespace after insertion of suggested word

### ISSUE THREAD

**Issue by danielmmmm** [Nordskog/SwiftKeyExi#3]
Hei! SwiftKey inserts a whitespace after words that were inserted from the suggestions pop-up. Unfortunately, SwiftKey does not remove this whitespace when an inserted suggestion is followed by punctuation.

This behaviour makes typing and inserting suggestions very inconsistent. Even worse is the fact that SwiftKey changed this behaviour in the past, and might do it again in the future.
Therefore, it would be great if Exi could remove the whitespace after inserted suggestions. A consistent behaviour would make typing much easier.

Alternatively, Exi could remove the whitespace only when a suggestion is followed by punctuation. But this would be more difficult to code, I assume.

**Comment by Nordskog** [comment]
Sorry, that was probably me rather than Swiftkey.
1.0.2 added the ability to remove auto-punctuation after punctuation. When enabled, it completely nuked all punctuation rules, including where to position it when preceded by whitespace.

This has corrected in commit https://github.com/Nordskog/SwiftKeyExi/commit/8636a84d56cedd92a0cb80e37c5cfa1351a02f56
In the meanwhile, disabling "No punctuation auto-space" (which should be disabled by default) should fix it for you.

**Comment by danielmmmm** [comment]
Thanks a lot, and thanks for this great module :-)

**Comment by Nordskog** [comment]
Punctuation should behave correctly as of https://github.com/Nordskog/SwiftKeyExi/commit/8636a84d56cedd92a0cb80e37c5cfa1351a02f56
