### ISSUE TITLE
Issue: Exi emoji panels incomplete on Android 10

### ISSUE THREAD

**Issue by MrSourceUnknown** [Nordskog/SwiftKeyExi#79]
While Android 10 emoji support was added to Exi, it doesn't show the complete list of emoji Android 10 supports. This is because the list of visible emoji is based on the Swiftkey default panels, which is incomplete.

Apps like WhatsApp, have a built in emoji keyboard that shows the _complete_ list of available Android 10 emoji's, and you can copy and paste them from there to all other applications. So it is clear the OS supports them, not sure why Swiftkey decided not to add them to their default panels.

I hope you can find a complete set of Android 10 emoji to add to the Exi panels, so we can use them throughout the OS. I hope you'll be able to do that without breaking compatibility with other OS versions.

Posted as issue as promised on the XDA thread.

**Comment by Nordskog** [comment]
Fixed in https://github.com/Nordskog/SwiftKeyExi/commit/c7846402c4758c9e0ec41505d5d27eb924f96535

Emoji pulled from Unicode's 13.0 emoji test list, so should hopefully include everything.
Mixed skin-tone variants are not included, because I'd either have to list all possible combinations, or come up with some new selection mechanism.

See the [2.6.0 release post](https://forum.xda-developers.com/showpost.php?p=81915643&postcount=1236) for more details.
