### ISSUE TITLE
Replace emoji icons

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Nordskog/SwiftKeyExi#8]
I'd like to have the emojis of WhatsApp on my keyboard, not the ones that come with the system. Is that possible? Thanks!

**Comment by Nordskog** [comment]
You might be surprised to know that was originally a planned feature, and most of the work necessary for doing it is already in place. Actually set up to use a specific style for each individual panel.

The reason I never quite finished it is because I sort of figured people who wanted a specific emoji font would just replace the system font instead, seeing as having them appear as something else _only_ in the keyboard would be rather weird.

**Comment by justanotheranonymoususer** [comment]
That's what I ended up doing, replacing the system font :) I didn't know that it's possible.

> seeing as having them appear as something else only in the keyboard would be rather weird.

That I agree with, but that's what WhatsApp does, and that's why I wanted this feature in the first place. I chat mostly in WhatsApp, so at least I wanted my chat app and my keyboard to agree on the emojis.

**Comment by Nordskog** [comment]
Better to replace system font, will not implement.
